# syntax=docker/dockerfile:1.3-labs

# gcc 11 and 12 in Debian 12 are incompatible with version of Boost libraries 
# in Litecoin's 'depends' build system
FROM debian:11 as build

ARG SOURCE_ZIP
ARG SOURCE_FOLDER

ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/London"

# Remove libdb++-dev after upstream fixes the problem with --disable-wallet requiring it
RUN <<-EOF
    apt-get -y update && \
    apt-get -y install \
    git \
    build-essential \
    libtool \
    pkg-config \
    libdb++-dev \
    curl \
    cmake \
    unzip
EOF

COPY $SOURCE_ZIP /tmp/
RUN unzip /tmp/$SOURCE_ZIP -d /tmp
RUN mkdir /opt/litecoin && mv /tmp/$SOURCE_FOLDER/* /opt/litecoin

WORKDIR /opt/litecoin

RUN <<-EOF
    make -C /opt/litecoin/depends/ -j $(getconf _NPROCESSORS_ONLN) NO_QT=1 NO_QR=1 NO_WALLET=1 NO_BDB=1
    ./autogen.sh
    ./configure \
        --disable-tests \
        --disable-bench \
        --disable-wallet \
        --without-gui \
        --prefix=/opt/litecoin/depends/x86_64-pc-linux-gnu/
    make -j $(getconf _NPROCESSORS_ONLN)
    make install
    find /opt/litecoin/depends/x86_64-pc-linux-gnu/bin/ -type f -executable ! -name "*.*" -exec strip -s {} \;
EOF

COPY litecoin.conf /opt/litecoin/.litecoin/litecoin.conf

RUN <<-EOF
    mkdir -p /opt/litecoin/.litecoin/db
    chown -R 65532:65532 /opt/litecoin/
EOF

FROM gcr.io/distroless/cc-debian12:nonroot as final

ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/London"

COPY --from=build /opt/litecoin/depends/x86_64-pc-linux-gnu/bin/ /opt/litecoin/bin/
COPY --from=build /opt/litecoin/.litecoin/ /opt/litecoin/.litecoin/

ENTRYPOINT ["/opt/litecoin/bin/litecoind", "-conf=/opt/litecoin/.litecoin/litecoin.conf", "-datadir=/opt/litecoin/.litecoin/db", "-txindex=1"]
