services:
  bitcoin:
    container_name: bitcoin
    image: flarefoundation/bitcoin:30.0-dless
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:9332:9332
    volumes:
      - bitcoin-data:/opt/bitcoin/.bitcoin/db
      - ./config/bitcoin/bitcoin.conf:/opt/bitcoin/.bitcoin/bitcoin.conf

  litecoin:
    container_name: litecoin
    image: flarefoundation/litecoin:0.21.4
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:8332:8332
    volumes:
      - litecoin-data:/opt/litecoin/.litecoin/db
      - ./config/litecoin/litecoin.conf:/opt/litecoin/.litecoin/litecoin.conf

  dogecoin:
    container_name: dogecoin
    image: flarefoundation/dogecoin:1.14.9
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:7332:7332
    volumes:
      - dogecoin-data:/opt/dogecoin/.dogecoin/db
      - ./config/dogecoin/dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

  xrpl:
    container_name: xrpl
    image: flarefoundation/xrpl:3.2.0-dless
    restart: on-failure:3
    environment:
      - TZ=Europe/London
    ports:
      - ${BIND_IP}:5005:5005   # port_rpc_admin_local
      - ${BIND_IP}:6006:6006   # port_ws_admin_local
      - ${BIND_IP}:51235:51235 # port_peer
      - ${BIND_IP}:51234:51234 # port_rpc_public
      - ${BIND_IP}:51233:51233 # port_ws_public
      - ${BIND_IP}:50051:50051 # port_grpc
    volumes:
      - xrpl-data:/opt/xrpld/.xrpld/db:rw
      - ./config/xrpl/xrpld.cfg:/opt/xrpld/.xrpld/xrpld.cfg:ro
      - ./config/xrpl/validators.txt:/opt/xrpld/.xrpld/validators.txt:ro

volumes:
  bitcoin-data:
  litecoin-data:
  dogecoin-data:
  xrpl-data:
