# syntax=docker/dockerfile:1.3-labs
FROM ubuntu:22.04 as build

ARG SOURCE_ZIP
ARG SOURCE_FOLDER

ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/London"

RUN <<-EOF
    apt-get -y update && \
    apt-get -y install \
    git \
    build-essential \
    libtool \
    autotools-dev \
    automake \
    pkg-config \
    bsdmainutils \
    libevent-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    libboost-chrono-dev \
    libboost-test-dev \
    libboost-thread-dev \
    libboost-program-options-dev \
    libssl-dev \
    net-tools \
    curl \
    jq \
    netcat \
    unzip
EOF

COPY $SOURCE_ZIP /tmp/
RUN unzip /tmp/$SOURCE_ZIP -d /tmp
RUN mkdir /opt/dogecoin && mv /tmp/$SOURCE_FOLDER/* /opt/dogecoin 

WORKDIR /opt/dogecoin

RUN <<-EOF
    bash ./autogen.sh && \
    bash ./configure --enable-hardening --disable-wallet --without-gui --disable-tests --disable-bench --prefix=/opt/dogecoin/build && \
    echo $(getconf _NPROCESSORS_ONLN) && \
    make -j $(getconf _NPROCESSORS_ONLN) && \
    make install && \
    mkdir -p /opt/dogecoin/.dogecoin/db && \
    chmod 755 /opt/dogecoin/.dogecoin/db && \
    chown -R 65532:65532 /opt/dogecoin/
EOF

COPY ./dogecoin.conf /opt/dogecoin/.dogecoin/dogecoin.conf

FROM gcr.io/distroless/cc-debian12:nonroot as final

COPY --from=build /opt/dogecoin/ /opt/dogecoin/

ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/London"
ENV PATH="/opt/dogecoin/build/bin:${PATH}"

# Libraries (ldd /opt/dogecoin/build/bin/dogecoind)
COPY --from=build /usr/lib/x86_64-linux-gnu/libboost*.so* /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libevent*.so* /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libzmq.so.5 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libcrypto.so.3 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libm.so.6 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libbsd.so.0 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libsodium.so.23 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libpgm-5.3.so.0 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libnorm.so.1 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libmd.so.0 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libkrb5.so.3 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libcom_err.so.2 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libkeyutils.so.1 /usr/lib/x86_64-linux-gnu/
COPY --from=build /usr/lib/x86_64-linux-gnu/libresolv.so.2 /usr/lib/x86_64-linux-gnu/

# Tools
COPY --from=build /usr/bin/curl /usr/bin/curl
COPY --from=build /usr/bin/jq /usr/bin/jq
COPY --from=build /usr/bin/netcat /usr/bin/netcat
COPY --from=build /usr/bin/netstat /usr/bin/netstat

ENTRYPOINT ["dogecoind", "-conf=/opt/dogecoin/.dogecoin/dogecoin.conf", "-datadir=/opt/dogecoin/.dogecoin/db", "-printtoconsole", "-txindex=1"]