# syntax=docker/dockerfile:1.3-labs
FROM debian:12 as build

ARG SOURCE_ZIP
ARG SOURCE_FOLDER

ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/London"

RUN <<-EOF
    apt-get -y update && \
    apt-get -y install \
    git \
    build-essential \
    cmake \
    libtool \
    pkg-config \
    curl 
    unzip
EOF

COPY $SOURCE_ZIP /tmp/
RUN unzip /tmp/$SOURCE_ZIP -d /tmp
RUN mkdir /opt/dogecoin && mv /tmp/$SOURCE_FOLDER/* /opt/dogecoin 

WORKDIR /opt/dogecoin

RUN <<-EOF
    make -C /opt/dogecoin/depends/ -j $(getconf _NPROCESSORS_ONLN) NO_QT=1 NO_QR=1 NO_WALLET=1 NO_BDB=1 && \
    ./autogen.sh && \
    ./configure \
        --disable-wallet \
        --without-gui \
        --disable-tests \
        --disable-bench \
        --prefix=/opt/dogecoin/depends/x86_64-pc-linux-gnu/ && \
    make -j $(getconf _NPROCESSORS_ONLN) && \
    make install && \
    find /opt/dogecoin/go/bin -type f -executable -exec strip -s {} + 2>/dev/null || true
EOF

COPY dogecoin.conf /opt/dogecoin/.dogecoin/dogecoin.conf

RUN <<-EOF
    mkdir -p /opt/dogecoin/.dogecoin/db && \
    chown -R 65532:65532 /opt/dogecoin/
EOF

FROM gcr.io/distroless/cc-debian12:nonroot as final

ENV DEBIAN_FRONTEND="noninteractive" TZ="Europe/London"

COPY --from=build /opt/dogecoin/depends/x86_64-pc-linux-gnu/bin/ /opt/dogecoin/bin/
COPY --from=build /opt/dogecoin/.dogecoin/ /opt/dogecoin/.dogecoin/

ENTRYPOINT ["/opt/dogecoin/bin/dogecoind", "-conf=/opt/dogecoin/.dogecoin/dogecoin.conf", "-datadir=/opt/dogecoin/.dogecoin/db", "-printtoconsole", "-txindex=1"]